name: Copy Kezdi.jl Documentation
on:
  repository_dispatch:
    types: [copy-kezdi-docs]
  workflow_dispatch:
jobs:
  copy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repository
        uses: actions/checkout@v4
      - name: Clone Kezdi.jl documentation
        run: |
          git clone -b gh-pages --single-branch --depth 1 https://github.com/codedthinking/Kezdi.jl.git/ temp-docs
      - name: Prepare documentation
        run: |
          mkdir -p Kezdi.jl
          cp -r temp-docs/dev/* Kezdi.jl/
          rm -rf temp-docs
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Kezdi.jl
          git commit -m "Update Kezdi.jl documentation" || exit 0
          git push
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    needs: copy-docs
    permissions:
      actions: write # needed to allow julia-actions/cache to proactively delete old caches that it has created
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Kezdi.jl
          publish_branch: Kezdi.jl
